services:
  db:
    image: postgres:15-bullseye
    restart: always
    environment:
      POSTGRES_DB: wb_db
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "8081:5432"